-- github.com/andy489

-- MS SQL Server, MySQL, Oracle, DB2
SELECT N,
CASE WHEN P IS NULL THEN 'Root' WHEN N NOT IN (SELECT P FROM BST WHERE P IS NOT NULL) THEN 'Leaf' ELSE 'Inner' END
FROM BST ORDER BY 1;

-- MySQL
SELECT N, IF(P IS NULL,'Root',IF((SELECT COUNT(*) FROM BST 
WHERE P=B.N)>0,'Inner','Leaf')) FROM BST AS B ORDER BY N;
