/*
MySQL & Oracle & MS SQL Server
*/
SELECT sum(CITY.POPULATION) 
FROM CITY, COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE AND COUNTRY.CONTINENT = 'Asia';

/*
MySQL & Oracle & MS SQL Server
Using JOIN
*/
SELECT sum(x.POPULATION)
FROM CITY x INNER JOIN COUNTRY y
            ON x.COUNTRYCODE = y.CODE
WHERE CONTINENT = 'Asia';
