/*
MySQL & Oracle & MS SQL Server
*/
SELECT CITY.NAME
FROM CITY, COUNTRY        
WHERE CITY.COUNTRYCODE = COUNTRY.CODE AND COUNTRY.CONTINENT = 'Africa';

/*
MySQL & Oracle & MS SQL Server
Using JOIN
*/
SELECT x.NAME
FROM CITY x INNER JOIN COUNTRY y
     ON x.COUNTRYCODE = y.CODE        
WHERE y.CONTINENT = 'Africa';
