-- github.com/andy489

-- MySQL
SELECT CITY, LENGTH(CITY) FROM STATION
ORDER BY LENGTH(CITY), CITY LIMIT 1;

SELECT CITY, LENGTH(CITY) FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1;

-- Oracle
SELECT CITY, length(CITY)
FROM (SELECT CITY FROM STATION
      ORDER BY length(CITY) asc, CITY)
WHERE ROWNUM = 1;
SELECT CITY, length(CITY)
FROM (SELECT CITY FROM STATION
      ORDER BY length(CITY) desc, CITY)
WHERE ROWNUM = 1;
